baseURL = 'https://arunm1407.github.io/android-interview-notes/'
locale = 'en-us'
title = 'Android Interview Prep'
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/arunm1407/android-interview-notes'
  BookSearch = true
  BookDateFormat = 'January 2, 2006'

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
